import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";
import GenericList from "App/Models/GenericList";

export default class extends BaseSeeder {
  public async run() {
    // Write your database queries inside the run method
    await GenericList.createMany([
      {grouper: "PAISES",itemCode: "COL", itemDescription: "Colombia"},
      {grouper: "PAISES",itemCode: "AFG", itemDescription: "Afganistán"},
      {grouper: "PAISES",itemCode: "ALB", itemDescription: "Albania"},
      {grouper: "PAISES",itemCode: "DEU", itemDescription: "Alemania"},
      {grouper: "PAISES",itemCode: "AND", itemDescription: "Andorra"},
      {grouper: "PAISES",itemCode: "AGO", itemDescription: "Angola"},
      {grouper: "PAISES",itemCode: "ATG", itemDescription: "Antigua y Barbuda"},
      {grouper: "PAISES",itemCode: "SAU", itemDescription: "Arabia Saudita"},
      {grouper: "PAISES",itemCode: "DZA", itemDescription: "Argelia"},
      {grouper: "PAISES",itemCode: "ARG", itemDescription: "Argentina"},
      {grouper: "PAISES",itemCode: "ARM", itemDescription: "Armenia"},
      {grouper: "PAISES",itemCode: "ABW", itemDescription: "Aruba"},
      {grouper: "PAISES",itemCode: "AUS", itemDescription: "Australia"},
      {grouper: "PAISES",itemCode: "AUT", itemDescription: "Austria"},
      {grouper: "PAISES",itemCode: "AZE", itemDescription: "Azerbaiyán"},
      {grouper: "PAISES",itemCode: "BHS", itemDescription: "Bahamas"},
      {grouper: "PAISES",itemCode: "BGD", itemDescription: "Bangladés"},
      {grouper: "PAISES",itemCode: "BRB", itemDescription: "Barbados"},
      {grouper: "PAISES",itemCode: "BHR", itemDescription: "Baréin"},
      {grouper: "PAISES",itemCode: "BEL", itemDescription: "Bélgica"},
      {grouper: "PAISES",itemCode: "BLZ", itemDescription: "Belice"},
      {grouper: "PAISES",itemCode: "BEN", itemDescription: "Benín"},
      {grouper: "PAISES",itemCode: "BLR", itemDescription: "Bielorrusia"},
      {grouper: "PAISES",itemCode: "MMR", itemDescription: "Birmania"},
      {grouper: "PAISES",itemCode: "BOL", itemDescription: "Bolivia"},
      {grouper: "PAISES",itemCode: "BIH", itemDescription: "Bosnia y Herzegovina"},
      {grouper: "PAISES",itemCode: "BWA", itemDescription: "Botsuana"},
      {grouper: "PAISES",itemCode: "BRA", itemDescription: "Brasil"},
      {grouper: "PAISES",itemCode: "BRN", itemDescription: "Brunéi"},
      {grouper: "PAISES",itemCode: "BGR", itemDescription: "Bulgaria"},
      {grouper: "PAISES",itemCode: "BFA", itemDescription: "Burkina Faso"},
      {grouper: "PAISES",itemCode: "BDI", itemDescription: "Burundi"},
      {grouper: "PAISES",itemCode: "BTN", itemDescription: "Bután"},
      {grouper: "PAISES",itemCode: "CPV", itemDescription: "Cabo Verde"},
      {grouper: "PAISES",itemCode: "KHM", itemDescription: "Camboya"},
      {grouper: "PAISES",itemCode: "CMR", itemDescription: "Camerún"},
      {grouper: "PAISES",itemCode: "CAN", itemDescription: "Canadá"},
      {grouper: "PAISES",itemCode: "QAT", itemDescription: "Catar"},
      {grouper: "PAISES",itemCode: "TCD", itemDescription: "Chad"},
      {grouper: "PAISES",itemCode: "CHL", itemDescription: "Chile"},
      {grouper: "PAISES",itemCode: "CHN", itemDescription: "China"},
      {grouper: "PAISES",itemCode: "CYP", itemDescription: "Chipre"},
      {grouper: "PAISES",itemCode: "VAT", itemDescription: "Ciudad del Vaticano"},
      {grouper: "PAISES",itemCode: "COM", itemDescription: "Comoras"},
      {grouper: "PAISES",itemCode: "PRK", itemDescription: "Corea del Norte"},
      {grouper: "PAISES",itemCode: "KOR", itemDescription: "Corea del Sur"},
      {grouper: "PAISES",itemCode: "CIV", itemDescription: "Costa de Marfil"},
      {grouper: "PAISES",itemCode: "CRI", itemDescription: "Costa Rica"},
      {grouper: "PAISES",itemCode: "HRV", itemDescription: "Croacia"},
      {grouper: "PAISES",itemCode: "CUB", itemDescription: "Cuba"},
      {grouper: "PAISES",itemCode: "DNK", itemDescription: "Dinamarca"},
      {grouper: "PAISES",itemCode: "DMA", itemDescription: "Dominica"},
      {grouper: "PAISES",itemCode: "ECU", itemDescription: "Ecuador"},
      {grouper: "PAISES",itemCode: "EGY", itemDescription: "Egipto"},
      {grouper: "PAISES",itemCode: "SLV", itemDescription: "El Salvador"},
      {grouper: "PAISES",itemCode: "ARE", itemDescription: "Emiratos Árabes Unidos"},
      {grouper: "PAISES",itemCode: "ERI", itemDescription: "Eritrea"},
      {grouper: "PAISES",itemCode: "SVK", itemDescription: "Eslovaquia"},
      {grouper: "PAISES",itemCode: "SVN", itemDescription: "Eslovenia"},
      {grouper: "PAISES",itemCode: "ESP", itemDescription: "España"},
      {grouper: "PAISES",itemCode: "USA", itemDescription: "Estados Unidos"},
      {grouper: "PAISES",itemCode: "EST", itemDescription: "Estonia"},
      {grouper: "PAISES",itemCode: "ETH", itemDescription: "Etiopía"},
      {grouper: "PAISES",itemCode: "PHL", itemDescription: "Filipinas"},
      {grouper: "PAISES",itemCode: "FIN", itemDescription: "Finlandia"},
      {grouper: "PAISES",itemCode: "FJI", itemDescription: "Fiyi"},
      {grouper: "PAISES",itemCode: "FRA", itemDescription: "Francia"},
      {grouper: "PAISES",itemCode: "GAB", itemDescription: "Gabón"},
      {grouper: "PAISES",itemCode: "GMB", itemDescription: "Gambia"},
      {grouper: "PAISES",itemCode: "GEO", itemDescription: "Georgia"},
      {grouper: "PAISES",itemCode: "GIB", itemDescription: "Gibraltar"},
      {grouper: "PAISES",itemCode: "GHA", itemDescription: "Ghana"},
      {grouper: "PAISES",itemCode: "GRD", itemDescription: "Granada"},
      {grouper: "PAISES",itemCode: "GRC", itemDescription: "Grecia"},
      {grouper: "PAISES",itemCode: "GRL", itemDescription: "Groenlandia"},
      {grouper: "PAISES",itemCode: "GTM", itemDescription: "Guatemala"},
      {grouper: "PAISES",itemCode: "GNQ", itemDescription: "Guinea Ecuatorial"},
      {grouper: "PAISES",itemCode: "GIN", itemDescription: "Guinea"},
      {grouper: "PAISES",itemCode: "GNB", itemDescription: "Guinea-Bisáu"},
      {grouper: "PAISES",itemCode: "GUY", itemDescription: "Guyana"},
      {grouper: "PAISES",itemCode: "HTI", itemDescription: "Haití"},
      {grouper: "PAISES",itemCode: "HND", itemDescription: "Honduras"},
      {grouper: "PAISES",itemCode: "HUN", itemDescription: "Hungría"},
      {grouper: "PAISES",itemCode: "IND", itemDescription: "India"},
      {grouper: "PAISES",itemCode: "IDN", itemDescription: "Indonesia"},
      {grouper: "PAISES",itemCode: "IRQ", itemDescription: "Irak"},
      {grouper: "PAISES",itemCode: "IRN", itemDescription: "Irán"},
      {grouper: "PAISES",itemCode: "IRL", itemDescription: "Irlanda"},
      {grouper: "PAISES",itemCode: "ISL", itemDescription: "Islandia"},
      {grouper: "PAISES",itemCode: "COK", itemDescription: "Islas Cook"},
      {grouper: "PAISES",itemCode: "MHL", itemDescription: "Islas Marshall"},
      {grouper: "PAISES",itemCode: "SLB", itemDescription: "Islas Salomón"},
      {grouper: "PAISES",itemCode: "ISR", itemDescription: "Israel"},
      {grouper: "PAISES",itemCode: "ITA", itemDescription: "Italia"},
      {grouper: "PAISES",itemCode: "JAM", itemDescription: "Jamaica"},
      {grouper: "PAISES",itemCode: "JPN", itemDescription: "Japón"},
      {grouper: "PAISES",itemCode: "JOR", itemDescription: "Jordania"},
      {grouper: "PAISES",itemCode: "KAZ", itemDescription: "Kazajistán"},
      {grouper: "PAISES",itemCode: "KEN", itemDescription: "Kenia"},
      {grouper: "PAISES",itemCode: "KGZ", itemDescription: "Kirguistán"},
      {grouper: "PAISES",itemCode: "KIR", itemDescription: "Kiribati"},
      {grouper: "PAISES",itemCode: "KWT", itemDescription: "Kuwait"},
      {grouper: "PAISES",itemCode: "LAO", itemDescription: "Laos"},
      {grouper: "PAISES",itemCode: "LSO", itemDescription: "Lesoto"},
      {grouper: "PAISES",itemCode: "LVA", itemDescription: "Letonia"},
      {grouper: "PAISES",itemCode: "LBN", itemDescription: "Líbano"},
      {grouper: "PAISES",itemCode: "LBR", itemDescription: "Liberia"},
      {grouper: "PAISES",itemCode: "LBY", itemDescription: "Libia"},
      {grouper: "PAISES",itemCode: "LIE", itemDescription: "Liechtenstein"},
      {grouper: "PAISES",itemCode: "LTU", itemDescription: "Lituania"},
      {grouper: "PAISES",itemCode: "LUX", itemDescription: "Luxemburgo"},
      {grouper: "PAISES",itemCode: "MDG", itemDescription: "Madagascar"},
      {grouper: "PAISES",itemCode: "MYS", itemDescription: "Malasia"},
      {grouper: "PAISES",itemCode: "MWI", itemDescription: "Malaui"},
      {grouper: "PAISES",itemCode: "MDV", itemDescription: "Maldivas"},
      {grouper: "PAISES",itemCode: "MLI", itemDescription: "Malí"},
      {grouper: "PAISES",itemCode: "MLT", itemDescription: "Malta"},
      {grouper: "PAISES",itemCode: "MAR", itemDescription: "Marruecos"},
      {grouper: "PAISES",itemCode: "MTQ", itemDescription: "Martinica"},
      {grouper: "PAISES",itemCode: "MUS", itemDescription: "Mauricio"},
      {grouper: "PAISES",itemCode: "MRT", itemDescription: "Mauritania"},
      {grouper: "PAISES",itemCode: "MEX", itemDescription: "México"},
      {grouper: "PAISES",itemCode: "FSM", itemDescription: "Micronesia"},
      {grouper: "PAISES",itemCode: "MDA", itemDescription: "Moldavia"},
      {grouper: "PAISES",itemCode: "MCO", itemDescription: "Mónaco"},
      {grouper: "PAISES",itemCode: "MNG", itemDescription: "Mongolia"},
      {grouper: "PAISES",itemCode: "MNE", itemDescription: "Montenegro"},
      {grouper: "PAISES",itemCode: "MOZ", itemDescription: "Mozambique"},
      {grouper: "PAISES",itemCode: "NAM", itemDescription: "Namibia"},
      {grouper: "PAISES",itemCode: "NRU", itemDescription: "Nauru"},
      {grouper: "PAISES",itemCode: "NPL", itemDescription: "Nepal"},
      {grouper: "PAISES",itemCode: "NIC", itemDescription: "Nicaragua"},
      {grouper: "PAISES",itemCode: "NER", itemDescription: "Níger"},
      {grouper: "PAISES",itemCode: "NGA", itemDescription: "Nigeria"},
      {grouper: "PAISES",itemCode: "NOR", itemDescription: "Noruega"},
      {grouper: "PAISES",itemCode: "NZL", itemDescription: "NuevaZelanda"},
      {grouper: "PAISES",itemCode: "OMN", itemDescription: "Omán"},
      {grouper: "PAISES",itemCode: "NLD", itemDescription: "Países Bajos"},
      {grouper: "PAISES",itemCode: "PAK", itemDescription: "Pakistán"},
      {grouper: "PAISES",itemCode: "PLW", itemDescription: "Palaos"},
      {grouper: "PAISES",itemCode: "PSE", itemDescription: "Palestina"},
      {grouper: "PAISES",itemCode: "PAN", itemDescription: "Panamá"},
      {grouper: "PAISES",itemCode: "PNG", itemDescription: "Papúa Nueva Guinea"},
      {grouper: "PAISES",itemCode: "PRY", itemDescription: "Paraguay"},
      {grouper: "PAISES",itemCode: "PER", itemDescription: "Perú"},
      {grouper: "PAISES",itemCode: "POL", itemDescription: "Polonia"},
      {grouper: "PAISES",itemCode: "PRT", itemDescription: "Portugal"},
      {grouper: "PAISES",itemCode: "PRI", itemDescription: "Puerto Rico"},
      {grouper: "PAISES",itemCode: "GBR", itemDescription: "Reino Unido"},
      {grouper: "PAISES",itemCode: "CAF", itemDescription: "República Centro Africana"},
      {grouper: "PAISES",itemCode: "CZE", itemDescription: "República Checa"},
      {grouper: "PAISES",itemCode: "MKD", itemDescription: "República de Macedonia"},
      {grouper: "PAISES",itemCode: "COG", itemDescription: "República del Congo"},
      {grouper: "PAISES",itemCode: "COD", itemDescription: "República Democrática del Congo"},
      {grouper: "PAISES",itemCode: "DOM", itemDescription: "República Dominicana"},
      {grouper: "PAISES",itemCode: "ZAF", itemDescription: "República Sudafricana"},
      {grouper: "PAISES",itemCode: "RWA", itemDescription: "Ruanda"},
      {grouper: "PAISES",itemCode: "ROU", itemDescription: "Rumanía"},
      {grouper: "PAISES",itemCode: "RUS", itemDescription: "Rusia"},
      {grouper: "PAISES",itemCode: "WSM", itemDescription: "Samoa"},
      {grouper: "PAISES",itemCode: "KNA", itemDescription: "San Cristóbal y Nieves"},
      {grouper: "PAISES",itemCode: "SMR", itemDescription: "San Marino"},
      {grouper: "PAISES",itemCode: "VCT", itemDescription: "San Vicente y las Granadinas"},
      {grouper: "PAISES",itemCode: "LCA", itemDescription: "Santa Lucía"},
      {grouper: "PAISES",itemCode: "STP", itemDescription: "Santo Tomé y Príncipe"},
      {grouper: "PAISES",itemCode: "SEN", itemDescription: "Senegal"},
      {grouper: "PAISES",itemCode: "SRB", itemDescription: "Serbia"},
      {grouper: "PAISES",itemCode: "SYC", itemDescription: "Seychelles"},
      {grouper: "PAISES",itemCode: "SLE", itemDescription: "SierraLeona"},
      {grouper: "PAISES",itemCode: "SGP", itemDescription: "Singapur"},
      {grouper: "PAISES",itemCode: "SYR", itemDescription: "Siria"},
      {grouper: "PAISES",itemCode: "SOM", itemDescription: "Somalia"},
      {grouper: "PAISES",itemCode: "LKA", itemDescription: "Sri Lanka"},
      {grouper: "PAISES",itemCode: "SWZ", itemDescription: "Suazilandia"},
      {grouper: "PAISES",itemCode: "SSD", itemDescription: "Sudándel Sur"},
      {grouper: "PAISES",itemCode: "SDN", itemDescription: "Sudán"},
      {grouper: "PAISES",itemCode: "SWE", itemDescription: "Suecia"},
      {grouper: "PAISES",itemCode: "CHE", itemDescription: "Suiza"},
      {grouper: "PAISES",itemCode: "SUR", itemDescription: "Surinam"},
      {grouper: "PAISES",itemCode: "THA", itemDescription: "Tailandia"},
      {grouper: "PAISES",itemCode: "TZA", itemDescription: "Tanzania"},
      {grouper: "PAISES",itemCode: "TJK", itemDescription: "Tayikistán"},
      {grouper: "PAISES",itemCode: "TLS", itemDescription: "Timor Oriental"},
      {grouper: "PAISES",itemCode: "TGO", itemDescription: "Togo"},
      {grouper: "PAISES",itemCode: "TON", itemDescription: "Tonga"},
      {grouper: "PAISES",itemCode: "TTO", itemDescription: "Trinidad y Tobago"},
      {grouper: "PAISES",itemCode: "TUN", itemDescription: "Túnez"},
      {grouper: "PAISES",itemCode: "TKM", itemDescription: "Turkmenistán"},
      {grouper: "PAISES",itemCode: "TUR", itemDescription: "Turquía"},
      {grouper: "PAISES",itemCode: "TUV", itemDescription: "Tuvalu"},
      {grouper: "PAISES",itemCode: "UKR", itemDescription: "Ucrania"},
      {grouper: "PAISES",itemCode: "UGA", itemDescription: "Uganda"},
      {grouper: "PAISES",itemCode: "URY", itemDescription: "Uruguay"},
      {grouper: "PAISES",itemCode: "UZB", itemDescription: "Uzbekistán"},
      {grouper: "PAISES",itemCode: "VUT", itemDescription: "Vanuatu"},
      {grouper: "PAISES",itemCode: "VEN", itemDescription: "Venezuela"},
      {grouper: "PAISES",itemCode: "VNM", itemDescription: "Vietnam"},
      {grouper: "PAISES",itemCode: "YEM", itemDescription: "Yemen"},
      {grouper: "PAISES",itemCode: "DJI", itemDescription: "Yibuti"},
      {grouper: "PAISES",itemCode: "ZMB", itemDescription: "Zambia"},
    ]);


    await GenericList.createMany([{grouper: "DEPARTAMENTOS",itemCode: "5", itemDescription: "Antioquia",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "99", itemDescription: "Vichada",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "97", itemDescription: "Vaupés",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "95", itemDescription: "Guaviare",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "94", itemDescription: "Guainía",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "91", itemDescription: "Amazonas",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "88", itemDescription: "Archipiélago de San Andrés; Providencia y Santa Catalina",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "86", itemDescription: "Putumayo",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "85", itemDescription: "Casanare",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "81", itemDescription: "Arauca",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "76", itemDescription: "Valle del Cauca",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "73", itemDescription: "Tolima",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "70", itemDescription: "Sucre",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "68", itemDescription: "Santander",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "66", itemDescription: "Risaralda",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "63", itemDescription: "Quindío",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "54", itemDescription: "Norte de Santander",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "52", itemDescription: "Nariño",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "50", itemDescription: "Meta",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "47", itemDescription: "Magdalena",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "44", itemDescription: "La Guajira",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "41", itemDescription: "Huila",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "27", itemDescription: "Chocó",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "25", itemDescription: "Cundinamarca",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "23", itemDescription: "Córdoba",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "20", itemDescription: "Cesar",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "19", itemDescription: "Cauca",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "18", itemDescription: "Caquetá",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "17", itemDescription: "Caldas",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "15", itemDescription: "Boyacá",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "13", itemDescription: "Bolívar",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "11", itemDescription: "Bogotá D.C.",  parentGrouper: "PAISES", parentItemCode: "COL"},
    {grouper: "DEPARTAMENTOS",itemCode: "8", itemDescription: "Atlántico",  parentGrouper: "PAISES", parentItemCode: "COL"},])

    await GenericList.createMany([
      {grouper: "MUNICIPIOS",itemCode: "2", itemDescription: "Abejorral",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "3", itemDescription: "Abriaquí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "4", itemDescription: "Alejandría",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "5", itemDescription: "Amagá",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "6", itemDescription: "Amalfi",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "7", itemDescription: "Andes",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "8", itemDescription: "Angelópolis",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "9", itemDescription: "Angostura",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "10", itemDescription: "Anorí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "12", itemDescription: "Apartadó",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "13", itemDescription: "Arboletes",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "14", itemDescription: "Argelia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "15", itemDescription: "Armenia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "16", itemDescription: "Barbosa",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "17", itemDescription: "Bello",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "18", itemDescription: "Betania",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "19", itemDescription: "Betulia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "20", itemDescription: "Ciudad Bolívar",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "21", itemDescription: "Briceño",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "22", itemDescription: "Buriticá",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "23", itemDescription: "Cáceres",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "24", itemDescription: "Caicedo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "25", itemDescription: "Caldas",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "26", itemDescription: "Campamento",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "27", itemDescription: "Cañasgordas",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "28", itemDescription: "Caracolí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "29", itemDescription: "Caramanta",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "30", itemDescription: "Carepa",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "31", itemDescription: "Carolina",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "32", itemDescription: "Caucasia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "33", itemDescription: "Chigorodó",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "34", itemDescription: "Cisneros",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "35", itemDescription: "Cocorná",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "36", itemDescription: "Concepción",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "37", itemDescription: "Concordia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "38", itemDescription: "Copacabana",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "39", itemDescription: "Dabeiba",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "40", itemDescription: "Don Matías",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "41", itemDescription: "Ebéjico",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "42", itemDescription: "El Bagre",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "44", itemDescription: "Envigado",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "45", itemDescription: "Fredonia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "46", itemDescription: "Giraldo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "47", itemDescription: "Girardota",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "48", itemDescription: "Gómez Plata",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "49", itemDescription: "Guadalupe",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "50", itemDescription: "Guarne",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "51", itemDescription: "Guatapé",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "52", itemDescription: "Heliconia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "53", itemDescription: "Hispania",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "55", itemDescription: "Ituango",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "56", itemDescription: "Belmira",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "57", itemDescription: "Jericó",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "58", itemDescription: "La Ceja",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "59", itemDescription: "La Estrella",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "60", itemDescription: "La Pintada",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "61", itemDescription: "La Unión",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "62", itemDescription: "Liborina",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "63", itemDescription: "Maceo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "64", itemDescription: "Marinilla",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "65", itemDescription: "Montebello",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "66", itemDescription: "Murindó",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "67", itemDescription: "Mutatá",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "68", itemDescription: "Nariño",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "69", itemDescription: "Necoclí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "70", itemDescription: "Nechí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "71", itemDescription: "Olaya",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "72", itemDescription: "Peñol",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "73", itemDescription: "Peque",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "74", itemDescription: "Pueblorrico",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "75", itemDescription: "Puerto Berrío",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "76", itemDescription: "Puerto Nare",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "77", itemDescription: "Puerto Triunfo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "78", itemDescription: "Remedios",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "79", itemDescription: "Retiro",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "80", itemDescription: "Rionegro",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "81", itemDescription: "Sabanalarga",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "82", itemDescription: "Sabaneta",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "83", itemDescription: "Salgar",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "84", itemDescription: "San Francisco",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "85", itemDescription: "San Jerónimo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "86", itemDescription: "San Luis",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "87", itemDescription: "San Pedro",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "88", itemDescription: "San Rafael",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "89", itemDescription: "San Roque",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "90", itemDescription: "San Vicente",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "91", itemDescription: "Santa Bárbara",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "92", itemDescription: "Santo Domingo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "93", itemDescription: "El Santuario",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "94", itemDescription: "Segovia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "95", itemDescription: "Sopetrán",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "96", itemDescription: "Támesis",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "97", itemDescription: "Tarazá",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "98", itemDescription: "Tarso",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "99", itemDescription: "Titiribí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "100", itemDescription: "Toledo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "101", itemDescription: "Turbo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "102", itemDescription: "Uramita",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "103", itemDescription: "Urrao",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "104", itemDescription: "Valdivia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "105", itemDescription: "Valparaíso",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "106", itemDescription: "Vegachí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "107", itemDescription: "Venecia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "108", itemDescription: "Yalí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "109", itemDescription: "Yarumal",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "110", itemDescription: "Yolombó",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "111", itemDescription: "Yondó",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "112", itemDescription: "Zaragoza",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "114", itemDescription: "Santafé de Antioquia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "115", itemDescription: "Santa Rosa de Osos",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "116", itemDescription: "San Andrés de Cuerquía",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "117", itemDescription: "Vigía del Fuerte",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "118", itemDescription: "San José de La Montaña",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "119", itemDescription: "San Juan de Urabá",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "120", itemDescription: "El Carmen de Viboral",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "121", itemDescription: "San Carlos",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "122", itemDescription: "Frontino",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "123", itemDescription: "Granada",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "124", itemDescription: "Jardín",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "125", itemDescription: "Sonsón",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "126", itemDescription: "Barranquilla",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "127", itemDescription: "Baranoa",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "128", itemDescription: "Candelaria",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "129", itemDescription: "Galapa",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "130", itemDescription: "Luruaco",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "131", itemDescription: "Malambo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "132", itemDescription: "Manatí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "133", itemDescription: "Piojó",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "134", itemDescription: "Polonuevo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "135", itemDescription: "Sabanagrande",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "136", itemDescription: "Sabanalarga",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "137", itemDescription: "Santa Lucía",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "138", itemDescription: "Santo Tomás",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "139", itemDescription: "Soledad",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "140", itemDescription: "Suan",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "141", itemDescription: "Tubará",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "142", itemDescription: "Usiacurí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "143", itemDescription: "Juan de Acosta",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "144", itemDescription: "Palmar de Varela",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "145", itemDescription: "Campo de La Cruz",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "146", itemDescription: "Repelón",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "147", itemDescription: "Puerto Colombia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "148", itemDescription: "Ponedera",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "8"},
{grouper: "MUNICIPIOS",itemCode: "149", itemDescription: "Bogotá D.C.",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "11"},
{grouper: "MUNICIPIOS",itemCode: "150", itemDescription: "Achí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "151", itemDescription: "Arenal",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "152", itemDescription: "Arjona",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "153", itemDescription: "Arroyohondo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "154", itemDescription: "Calamar",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "155", itemDescription: "Cantagallo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "156", itemDescription: "Cicuco",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "157", itemDescription: "Córdoba",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "158", itemDescription: "Clemencia",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "159", itemDescription: "El Guamo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "160", itemDescription: "Magangué",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "161", itemDescription: "Mahates",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "162", itemDescription: "Margarita",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "163", itemDescription: "Montecristo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "164", itemDescription: "Mompós",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "1", itemDescription: "Medellín",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "5"},
{grouper: "MUNICIPIOS",itemCode: "165", itemDescription: "Morales",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "166", itemDescription: "Norosí",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "167", itemDescription: "Pinillos",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "168", itemDescription: "Regidor",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "169", itemDescription: "Río Viejo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "170", itemDescription: "San Estanislao",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "171", itemDescription: "San Fernando",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "172", itemDescription: "San Juan Nepomuceno",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "173", itemDescription: "Santa Catalina",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "174", itemDescription: "Santa Rosa",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "175", itemDescription: "Simití",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "176", itemDescription: "Soplaviento",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "177", itemDescription: "Talaigua Nuevo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "178", itemDescription: "Tiquisio",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "179", itemDescription: "Turbaco",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "180", itemDescription: "Turbaná",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "181", itemDescription: "Villanueva",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "182", itemDescription: "Barranco de Loba",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "183", itemDescription: "Santa Rosa del Sur",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "184", itemDescription: "Hatillo de Loba",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "185", itemDescription: "El Carmen de Bolívar",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "186", itemDescription: "San Martín de Loba",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "187", itemDescription: "Altos del Rosario",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "188", itemDescription: "San Jacinto del Cauca",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "189", itemDescription: "San Pablo de Borbur",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "190", itemDescription: "San Jacinto",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "191", itemDescription: "El Peñón",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "192", itemDescription: "Cartagena",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "193", itemDescription: "María la Baja",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "194", itemDescription: "San Cristóbal",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "195", itemDescription: "Zambrano",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "13"},
{grouper: "MUNICIPIOS",itemCode: "196", itemDescription: "Tununguá",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "15"},
{grouper: "MUNICIPIOS",itemCode: "197", itemDescription: "Motavita",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "15"},
{grouper: "MUNICIPIOS",itemCode: "198", itemDescription: "Ciénega",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "15"},
{grouper: "MUNICIPIOS",itemCode: "199", itemDescription: "Tunja",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "15"},
{grouper: "MUNICIPIOS",itemCode: "200", itemDescription: "Almeida",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "15"},
{grouper: "MUNICIPIOS",itemCode: "201", itemDescription: "Aquitania",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "15"},
{grouper: "MUNICIPIOS",itemCode: "202", itemDescription: "Arcabuco",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "15"},
{grouper: "MUNICIPIOS",itemCode: "203", itemDescription: "Berbeo",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "15"},
{grouper: "MUNICIPIOS",itemCode: "204", itemDescription: "Betéitiva",  parentGrouper: "DEPARTAMENTOS", parentItemCode: "15"},
    ])
    
  }
}
